name: CI/CD Pipeline - my-web-app

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement de déploiement'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      deploy_target:
        description: 'Plateforme de déploiement'
        required: true
        default: 'docker-compose'
        type: choice
        options:
          - docker-compose
          - kubernetes

env:
  PYTHON_VERSION: '3.11'
  APP_NAME: my-web-app
  APP_VERSION: 1.0.0

jobs:
  validate-xml:
    name: Valider la configuration XML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml

      - name: Validate XML against XSD
        run: |
          python scripts/validate-xml.py config.xml

  generate-docker-compose:
    name: Générer Docker Compose
    runs-on: ubuntu-latest
    needs: validate-xml
    if: github.event.inputs.deploy_target == 'docker-compose' || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml pyyaml

      - name: Generate Docker Compose YAML
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment || 'dev' }}
          python scripts/generate-yaml.py config.xml --type docker-compose --environment $ENVIRONMENT --output generated/docker-compose-$ENVIRONMENT.yaml

      - name: Validate Docker Compose
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment || 'dev' }}
          docker-compose -f generated/docker-compose-$ENVIRONMENT.yaml config

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-${{ github.event.inputs.environment || 'dev' }}
          path: generated/docker-compose-*.yaml

  generate-kubernetes:
    name: Générer Kubernetes Manifests
    runs-on: ubuntu-latest
    needs: validate-xml
    if: github.event.inputs.deploy_target == 'kubernetes' || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml pyyaml

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Generate Kubernetes YAML
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment || 'dev' }}
          python scripts/generate-yaml.py config.xml --type kubernetes --environment $ENVIRONMENT --output generated/kubernetes-$ENVIRONMENT.yaml

      - name: Validate Kubernetes manifests
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment || 'dev' }}
          kubectl --dry-run=client -f generated/kubernetes-$ENVIRONMENT.yaml apply

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-${{ github.event.inputs.environment || 'dev' }}
          path: generated/kubernetes-*.yaml

  build-services:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: validate-xml
    if: github.event_name == 'push' || github.event.inputs.environment != ''
    strategy:
      matrix:
        service:
          - web
          - api
          - db
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ${{ matrix.service }}
        run: |
          echo "Building service: ${{ matrix.service }}"
          # Add your build commands here

  deploy-docker-compose:
    name: Déployer sur Docker Compose
    runs-on: ubuntu-latest
    needs: [generate-docker-compose, build-services]
    if: github.event.inputs.deploy_target == 'docker-compose' && github.event.inputs.environment != ''
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-compose-${{ github.event.inputs.environment }}

      - name: Deploy
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          docker-compose -f generated/docker-compose-$ENVIRONMENT.yaml up -d
          docker-compose -f generated/docker-compose-$ENVIRONMENT.yaml ps

  deploy-kubernetes:
    name: Déployer sur Kubernetes
    runs-on: ubuntu-latest
    needs: [generate-kubernetes, build-services]
    if: github.event.inputs.deploy_target == 'kubernetes' && github.event.inputs.environment != ''
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: kubernetes-${{ github.event.inputs.environment }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          # Configure cluster access
          echo "Configuring kubectl..."

      - name: Deploy to Kubernetes
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          kubectl apply -f generated/kubernetes-$ENVIRONMENT.yaml
          kubectl get deployments
          kubectl get services
          kubectl get pods
