name: CI/CD Pipeline - DevOps Config

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement de déploiement'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      deploy_target:
        description: 'Plateforme de déploiement'
        required: true
        default: 'docker-compose'
        type: choice
        options:
          - docker-compose
          - kubernetes

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  validate-xml:
    name: Valider la configuration XML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml
      
      - name: Validate XML against XSD
        run: |
          python -c "
          from lxml import etree
          import sys
          
          xml_doc = etree.parse('examples/sample-config.xml')
          xsd_doc = etree.parse('schemas/config.xsd')
          xsd_schema = etree.XMLSchema(xsd_doc)
          
          if not xsd_schema.validate(xml_doc):
              print('❌ Erreurs de validation XML:')
              for error in xsd_schema.error_log:
                  print(f'  Ligne {error.line}: {error.message}')
              sys.exit(1)
          
          print('✅ Validation XML réussie')
          "

  generate-docker-compose:
    name: Générer Docker Compose
    runs-on: ubuntu-latest
    needs: validate-xml
    if: github.event.inputs.deploy_target == 'docker-compose' || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml pyyaml
      
      - name: Generate Docker Compose YAML
        run: |
          ENVIRONMENT=${GITHUB_EVENT_INPUTS_ENVIRONMENT:-dev}
          python -c "
          from lxml import etree
          import os
          
          xml_doc = etree.parse('examples/sample-config.xml')
          xslt_doc = etree.parse('xslt/docker-compose.xslt')
          xslt_transformer = etree.XSLT(xslt_doc)
          result = xslt_transformer(xml_doc, environment=etree.XSLT.strparam('$ENVIRONMENT'))
          
          os.makedirs('generated', exist_ok=True)
          with open(f'generated/docker-compose-$ENVIRONMENT.yaml', 'w') as f:
              f.write(str(result))
          
          print(f'✅ Fichier docker-compose-$ENVIRONMENT.yaml généré')
          "
      
      - name: Validate Docker Compose
        run: |
          ENVIRONMENT=${GITHUB_EVENT_INPUTS_ENVIRONMENT:-dev}
          docker-compose -f generated/docker-compose-$ENVIRONMENT.yaml config
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-${{ github.event.inputs.environment || 'dev' }}
          path: generated/docker-compose-*.yaml

  generate-kubernetes:
    name: Générer Kubernetes Manifests
    runs-on: ubuntu-latest
    needs: validate-xml
    if: github.event.inputs.deploy_target == 'kubernetes' || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml pyyaml
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Generate Kubernetes YAML
        run: |
          ENVIRONMENT=${GITHUB_EVENT_INPUTS_ENVIRONMENT:-dev}
          python -c "
          from lxml import etree
          import os
          
          xml_doc = etree.parse('examples/sample-config.xml')
          xslt_doc = etree.parse('xslt/kubernetes.xslt')
          xslt_transformer = etree.XSLT(xslt_doc)
          result = xslt_transformer(xml_doc, environment=etree.XSLT.strparam('$ENVIRONMENT'))
          
          os.makedirs('generated', exist_ok=True)
          with open(f'generated/kubernetes-$ENVIRONMENT.yaml', 'w') as f:
              f.write(str(result))
          
          print(f'✅ Fichier kubernetes-$ENVIRONMENT.yaml généré')
          "
      
      - name: Validate Kubernetes manifests
        run: |
          ENVIRONMENT=${GITHUB_EVENT_INPUTS_ENVIRONMENT:-dev}
          kubectl --dry-run=client -f generated/kubernetes-$ENVIRONMENT.yaml apply
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-${{ github.event.inputs.environment || 'dev' }}
          path: generated/kubernetes-*.yaml

  deploy-docker-compose:
    name: Déployer sur Docker Compose
    runs-on: ubuntu-latest
    needs: generate-docker-compose
    if: github.event.inputs.deploy_target == 'docker-compose' && github.event.inputs.environment != ''
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-compose-${{ github.event.inputs.environment }}
      
      - name: Setup Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      
      - name: Deploy
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          docker-compose -f generated/docker-compose-$ENVIRONMENT.yaml up -d
          docker-compose -f generated/docker-compose-$ENVIRONMENT.yaml ps

  deploy-kubernetes:
    name: Déployer sur Kubernetes
    runs-on: ubuntu-latest
    needs: generate-kubernetes
    if: github.event.inputs.deploy_target == 'kubernetes' && github.event.inputs.environment != ''
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: kubernetes-${{ github.event.inputs.environment }}
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Configure kubectl
        run: |
          # Configurer l'accès au cluster Kubernetes
          # echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          # export KUBECONFIG=kubeconfig
          echo "Configuration kubectl..."
      
      - name: Load secrets from AWS Secrets Manager
        run: |
          # Exemple: Charger les secrets depuis AWS Secrets Manager
          # aws secretsmanager get-secret-value --secret-id ${{ github.event.inputs.environment }}/db/password
          echo "Chargement des secrets..."
      
      - name: Deploy to Kubernetes
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          kubectl apply -f generated/kubernetes-$ENVIRONMENT.yaml
          kubectl get deployments
          kubectl get services
          kubectl get pods

  notify:
    name: Notification
    runs-on: ubuntu-latest
    needs: [validate-xml, generate-docker-compose, generate-kubernetes]
    if: always()
    steps:
      - name: Send notification
        run: |
          echo "Pipeline terminé"
          # Ajouter votre logique de notification ici (Slack, email, etc.)
